# Generated by Django 5.2.12 on 2026-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='слоган')),
                ('description', models.TextField(verbose_name='описание')),
                ('genre', models.CharField(max_length=120, verbose_name='жанр')),
                ('status', models.CharField(choices=[('dev', 'В разработке'), ('ea', 'Ранний доступ'), ('released', 'Выпущена')], default='dev', max_length=20, verbose_name='статус')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата релиза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('role', models.CharField(max_length=120, verbose_name='роль')),
                ('bio', models.TextField(blank=True, verbose_name='био')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'участник команды',
                'verbose_name_plural': 'команда',
                'ordering': ['order', 'name'],
            },
        ),
    ]
