# Generated by Django 5.2.12 on 2026-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, help_text='JPEG или PNG, желательно 16:9', upload_to='games/covers/', verbose_name='обложка'),
        ),
    ]
